name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devops-bootcamp-welcome" #Must be unique in Heroku
          heroku_email: "anjithpaul.mec@gmail.com"
      - name: Build gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Run app
        run: ./gradlew bootRun
